---
abstract: "Sugar Syntax for moose 'has' fields"
author:
  - 'Kent Fredric <kentnl at cpan.org>'
build_requires:
  Module::Build: 0.35
configure_requires:
  Module::Build: 0.35
generated_by: 'Dist::Zilla version 1.093280'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Has-Sugar
provides:
  MooseX::Has::Sugar:
    file: lib/MooseX/Has/Sugar.pm
    version: 0.0405
  MooseX::Has::Sugar::Minimal:
    file: lib/MooseX/Has/Sugar/Minimal.pm
    version: 0.0405
  MooseX::Has::Sugar::Saccharin:
    file: lib/MooseX/Has/Sugar/Saccharin.pm
    version: 0.0405
requires:
  Carp: 0
  Moose: 0.84
  MooseX::Types: 0.10
  MooseX::Types::Moose: 0
  Sub::Exporter: 0
  Test::Exception: 0
  Test::More: 0
  namespace::autoclean: 0
resources:
  repository: http://github.com/kentfredric/MooseX-Has-Sugar
version: 0.0405
